config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'search#search'
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :patch]
  end
  resources :tags, only: [:index, :show]
  resources :categorys, only: [:show]
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'calendar', to: 'users#calendar'
    put 'hide' => 'users#hide', as: 'users_hide'
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: [:index, :destroy]
  resources :chats, only: [:show, :create]

end

app/models/notification.rb
class Notification < ApplicationRecord

  #スコープ(新着順)
  default_scope->{order(created_at: :desc)}

  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true
  belongs_to :chat, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
   before_action :set_category_tag, only: [:index]

  def index
    #current_userの投稿に紐づいた通知一覧
    @notifications = Notification.where(visited_id: current_user.id,checked: false ).where.not(visitor_id: current_user.id).to_a
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifications.each do |notification|
      notification.update_attributes(checked: true)
    end
    @checked_notifications = Notification.where(visited_id: current_user.id, checked: true ).where.not(visitor_id: current_user.id)
  end

  def destroy
    notification = Notification.find(params[:id])
    notification.destroy
    redirect_to notifications_path
  end

  def destroy_all
    #通知を全削除
    @checked_notifications = Notification.where(visited_id: current_user.id, checked: true ).where.not(visitor_id: current_user.id)
    @checked_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
    @visitor = notification.visitor
    @visited = notification.visited
    @comment = nil
    @visiter_comment = notification.post_comment_id
    #notification.actionがfollowかlikeかcommentか
    case notification.action
    when "follow" then
      tag.a(notification.visitor.name, href: user_path(@visitor))+"さんがあなたをフォローしました"
    when "like" then
      tag.a(notification.visitor.name, href: user_path(@visitor))+"さんがあなたの"+tag.a('投稿', href: post_path(notification.post_id))+"にいいねしました"
    when "comment" then
      @comment = PostComment.find_by(id: @visitor_comment)&.content
      if @visited == notification.post.user
        tag.a(@visitor.name, href: user_path(@visitor))+"さんがあなたの"+tag.a('投稿', href: post_path(notification.post_id))+"にコメントしました"
      else
        tag.a(@visitor.name, href: user_path(@visitor))+"さんが"+(notification.post.user.name)+"さんの"+tag.a('投稿', href: post_path(notification.post_id))+"にコメントしました"
      end
    when "chat" then
       tag.a(@visitor.name, href: user_path(@visitor))+"さんが"+tag.a('Chat', href: chat_path(notification.visitor))+"にメッセージを送りました"
    end
  end
  
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/views/notifications/_notifications.html.erb
<% notifications.each do |notification| %>
  <div class="notifications__index--list">
    <% visitor = notification.visitor %>
    <% post = notification.post %>
    <div class="notifications__index--container">
      <%= link_to user_path(visitor) do %>
        <p><%= attachment_image_tag visitor, :profile_image, format: 'jpg', fallback: "no_image.jpg", class: "profile_image"  %></p>
      <% end %>
      <%= notification_form(notification) %><span class="time"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
      <%= link_to "" , notification_path(notification), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "far fa-trash-alt"  %>
    </div>
  </div>
<% end %>

app/views/notifications/index.html.erb
<div class="notifications">
  <div class="notifications-row">
    <div class="notifications__headar">
      <div class="notifications__headar--title">
        <p class="title">Notification List</p>
      </div>
    </div>

    <div class="notifications__tab">
      <ul id="tab-menu">
        <li><a href="#tab1" class="active">新着通知</a></li>
        <li><a href="#tab2" class="">既読通知</a></li>
      </ul>

    <div id="tab-contents">
      <div id="tab1" class="tab">
        <% if @notifications.present? %>
          <div class="notifications__index">
            <%= render "notifications/notifications", notifications: @notifications  %>
          </div>
        <% else %>
          <div class="no-users">
            <p class="no-user">通知はありません</p>
          </div>
      　<% end %>
      </div>
  
      <div id="tab2" class="tab">
        <% if @checked_notifications.present? %>
          <div class="notifications__index">
            <div class="notifications__index--destroy_all">
              <%= link_to " 全削除" , notifications_destroy_all_path, method: :delete, data: { confirm: '本当に全て削除しますか？' }, class: "fas fa-trash-alt fa-lg"  %>
            </div>
            <%= render "notifications/notifications", notifications: @checked_notifications  %>
          </div>
        <% else %>
          <div class="no-users">
            <p class="no-user">通知はありません</p>
          </div>
      　<% end %>
      </div>
    </div>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>

<script>
$('#tab-contents .tab[id != "tab1"]').hide();

$('#tab-menu a').on('click', function(event) {
  $("#tab-contents .tab").hide();
  $("#tab-menu .active").removeClass("active");
  $(this).addClass("active");
  $($(this).attr("href")).show();
  event.preventDefault();
});
</script>