config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'search#search'
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :patch]
  end
  resources :tags, only: [:index, :show]
  resources :categorys, only: [:show]
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'calendar', to: 'users#calendar'
    put 'hide' => 'users#hide', as: 'users_hide'
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: [:index, :destroy]
  resources :chats, only: [:show, :create]

end

app/models/user.rb
class User < ApplicationRecord

 validates :name, presence: true, length: { in: 2..15 }, uniqueness: true
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: { maximum: 80 }
  attachment :profile_image

  # dependent: :destroy 親モデルを削除する際に、その親モデルに紐づく「子モデル」も一緒に削除できる
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :post_comments, dependent: :destroy

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # 被フォロー関係を通じて参照→自分をフォローしている人
  # through（スルー）は、あるリレーションを他のテーブルを通して実現する際に用いる
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  # 紐付ける名前とクラス名が異なるため、明示的にクラス名とIDを指定して紐付け
  # active_notifications：自分からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # passive_notifications：相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # -----------------フォロー機能------------------
  def follow(user_id)
    # createメソッドはnewとsaveを合わせた挙動
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    # ユーザーのフォローを外す
    # relationshipsテーブルには対応するレコードはただ一つ
    # そのためfind_byによって1レコードを特定し、destroyメソッドで削除する
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    # フォローしていればtrueを返す
    # include?は対象の配列に引数のものが含まれていればtrue、含まれていなければfalseを返す
    followings.include?(user)
  end
  # ------------------------------------------------

  # --------------------通知機能--------------------
  def create_notification_follow(current_user)
    notification = Notification.find_by(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if notification.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  # ------------------------------------------------

  def active_for_authentication?
    super && (self.is_valid == false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :calendar_correct_user, only: [:calendar]
  before_action :redirect_to_users, only: [:show]
  before_action :is_valid_users, only: [:show]
  before_action :set_category_tag

  def show
    @user = User.find_by(id: params[:id])
    case params[:sort]
    when "likes_count desc"
      @posts = @user.posts.where(status: 0).includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    when "draft desc"
      @posts = @user.posts.where(status: 1)
    when "like_post desc"
      likes = Like.where(user_id: current_user.id).pluck(:post_id)
      @posts = Post.find(likes)
    else
      @posts = @user.posts.order(created_at: :desc).where(status: 0)
    end
  end

  def index
    @users = User.where(is_valid: false)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "変更を保存しました。"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def calendar
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def hide
    @user = User.find(params[:user_id])
    #is_validカラムにフラグを立てる(defaultはfalse)
    @user.update(is_valid: true)
    #ログアウトさせる
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def calendar_correct_user
    @user = User.find(params[:user_id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def redirect_to_users
    @user = User.find_by(id: params[:id])
    if @user.blank?
      redirect_to users_path
    end
  end

  def is_valid_users
    @user = User.find_by(id: params[:id])
    unless @user.is_valid == false
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<% users.each do |user| %>
  <div class="user-index__card">
    <%= link_to user_path(user.id) do %>
      <div class="user-index__card-image">
        <div class="user-index__card--profile-image">
          <%= attachment_image_tag user, :profile_image,format: 'jpg', fallback: "no_image.jpg"  %>
        </div>
        <div class="user-index__card--color"></div>
      </div>
      <div class="user-index__card--info">
        <p class="user-index__card--name">
          <%= user.name %>
        </p>
        <p class="user-index__card--introduction">
          <%= safe_join("#{user.introduction}".split("\n")).truncate(40) %>
        </p>
      </div>
    <% end %>
    <div id="relationship_<%= user.id %>">
      <%= render partial: "relationships/relationships", locals: { user: user } %>
    </div>
  </div>
<% end %>

app/views/users/calendar.html.erb
<div class="usercalendar">
  <div class="usercalendar-row">
    <div class="usercalendar__headar">
      <div class="usercalendar__headar--title">
        <p>Calendar</p>
      </div>
    </div>
    <div class="usercalendar__main">
      <%= month_calendar events: @posts do |date, posts| %>
        <%= date.day %>
         <% posts.each do |post| %>
         <div class="usercalendar__main--post">
            <%= link_to post_path(post.id) do %>
              <%= attachment_image_tag post, :image, format: 'jpg', class: "usercalendar__main--image" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="userinfo">
  <div class="userinfo__edit">
    <div class="userinfo__title">
      <h2 class="userinfo__title--name">Profile</h2>
    </div>
    <% if @user.errors.any? %>
      <div id= error_explanation>
       <h2><%= pluralize(@user.errors.count, "件") %> のエラーが発生しました</h2>
       <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class=><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="userinfo__form">
      <%= form_with model: @user, local:true do |f| %>
        <div class="userinfo__form-field">
          <p><%= f.label :プロフィール画像, class: "userinfo__form-field--title" %></p>
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "200x200", id: "img_prev", class: "userinfo__form-field--image" %><br />
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="userinfo__form-field">
          <p><%= f.label :ニックネーム, class: "userinfo__form-field--title" %></p>
          <%= f.text_field :name, class: "userinfo__form-field--name" %>
        </div>
        <div class="userinfo__form-field">
          <p><%= f.label :自己紹介, class: "userinfo__form-field--title" %></p>
          <%= f.text_area :introduction, class: "userinfo__form-field--introduction"  %>
        </div>
        <%= f.submit "登録する", class: "actions-btn" %>
      <% end %>
      <div class="hide">
        <%= link_to "退会する", user_users_hide_path(@user), method: :put, "data-confirm" => "本当に退会しますか？", class: "actions-btn hide-btn" %>
      </div>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>


<script>
$(document).on("turbolinks:load", function(){
  function readURL(input) {
    if(input.files && input.files[0]){
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#user_profile_image").change(function(){
    readURL(this);
  });
});
</script>

app/views/users/index.html.erb
<div class="users">
  <div class="users__row">
    <div class="users__headar">
      <div class="users__headar--title">
        <p>User List</p>
      </div>
    </div>
    <div class="user-index">
      <%= render 'users', users: @users %>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show">
  <div class="user-show__row">
    <!--プロフィール-->
    <div class="user-show__header">
      <div class="user-show__profile">
        <%= attachment_image_tag @user, :profile_image,format: 'jpg', fallback: "no_image.jpg", class: "user-show__profile-image" %>
        <div class="user-show__profile-title">
          <h7 class="user-show__profile-title--name">
            <%= @user.name %>
          </h7>
          <p class="user-show__profile-title--introduction">
            <%= safe_join("#{@user.introduction}".split("\n"),tag(:br)) %>
          </p>
        </div>
        <!--フォロー機能-->
        <div class="user-show__usercount">
          <ul>
            <li class="user-show__usercount--item">
              <%= link_to user_followings_path(@user) do %>
                <%= @user.followings.where(is_valid: false).count %><span class="itemname">フォロー</span>
              <% end %>
            </li>
            <li class="user-show__usercount--item">
              <%= link_to user_followers_path(@user) do %>
                <%= @user.followers.where(is_valid: false).count %><span class="itemname">フォロワー</span>
              <% end %>
            </li>
            <li class="user-show__usercount--item">
              <%= @user.posts.where(status: 0).count %><span class="itemname">投稿</span>
            </li>
            <li class="user-show__usercount--item">
              <div class="user-show__follwing">
                <div id="relationship_<%= @user.id %>">
                  <%= render partial: "relationships/relationships", locals: { user: @user } %>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div class="user-show__edit-area">
          <% if @user.id == current_user.id %>
            <div>
              <%= link_to "プロフィール編集", edit_user_path(@user), class: "user-show__btn" %>
            </div>
            <div>
              <%= link_to "カレンダー", user_calendar_path(@user), class: "user-show__btn" %>
            </div>

          <% end %>
          <p id="notice">
           <% if flash[:notice] %>
            <%= flash[:notice] %>
           <% end %>
          </p>
         </div>
         <div class="user-show__edit-area follwer">
            <div class="user-show__follwing">
              <div id="relationship_<%= @user.id %>">
                <%= render partial: "relationships/relationships", locals: { user: @user } %>
              </div>
            </div>
          </div>
      </div>
    </div>

    <!--投稿並べ替えリンク-->
    <div class="user-show__posts-link">
      <ul class="tab-list list-unstyled">
        <li class="user-show__posts-link--item ">
          <%= link_to "新着順" %>
        </li>
        <li class="user-show__posts-link--item ">
          <%= link_to "いいね数順", sort: 'likes_count desc' %>
        </li>
        <% if @user == current_user %>
          <li class="user-show__posts-link--item ">
            <%= link_to "下書き", sort: 'draft desc' %>
          </li>
          <li class="user-show__posts-link--item ">
            <%= link_to "いいね済み投稿", sort: 'like_post desc' %>
          </li>
        <% end %>
      </ul>
    </div>
    <!--投稿一覧-->
    <div class="tabbox-contents">
      <div class="user-posts post-index__posts tabbox box-show">
        <%= render 'posts/index', posts: @posts %>
      </div>

  </div>
</div>