config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'search#search'
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :patch]
  end
  resources :tags, only: [:index, :show]
  resources :categorys, only: [:show]
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'calendar', to: 'users#calendar'
    put 'hide' => 'users#hide', as: 'users_hide'
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: [:index, :destroy]
  resources :chats, only: [:show, :create]

end

app/models/post.rb
class Post < ApplicationRecord

  validates :image, presence: true
  validates :introduction, presence: true, length: { in: 2..300 }
  #ジャンルの選択が「--」の時は保存できないようにする
  validates :category_id, numericality: { other_than: 1 }

  belongs_to :user
  attachment :image
  # addressカラムを基準に緯度経度を算出する。
  geocoded_by :address
  # 住所変更時に緯度経度も変更する。
  after_validation :geocode, if: :address_changed?

  # 中間テーブルにdependent: :destroyオプションを付けることで、Postが削除されると同時にPostとTagの関係が削除される
  has_many :post_tags, dependent: :destroy
  # throughオプションを使う場合、先にその中間テーブルとの関連付けを行う
  # throughオプションによってpost_tagsテーブルを通してtagsテーブルとの関連付けを行う
  # これを行うことで、Post.tagsとすればPostに紐付けられたTagの取得が可能になる
  has_many :tags, through: :post_tags

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :post_comments, dependent: :destroy

  has_many :notifications, dependent: :destroy

  enum status: { 投稿する: 0, 下書きする: 1 }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # --------------------タグ機能-------------------
  def save_tag(sent_tags)
    # self.メソッド名は
    # createアクションにて保存した@postに紐付いているタグが存在する場合、「タグの名前を配列として」全て取得
    # pluckは、1つのモデルで使用されているテーブルからカラム (1つでも複数でも可) を取得するクエリを送信するのに使用できる
    # 今回ではtagsテーブルからtag_nameカラムを取得するクエリを送信
    # selectと異なり、pluckはデータベースから受け取った結果を直接Rubyの配列に変換してくれる
    # unless~は、「タグが存在しているか」を確認
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsする
    # 文字列の配列でも下記のように引き算できる。
    # a = ["first", "second", "third"]　 b = ["first", "third", "forth"]
    # a - b => ["second"]　 b - a => ["forth"]
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    # 古いタグを削除する
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを追加しデータベースに保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end
  # ------------------------------------------------

  # --------------------通知機能-------------------
  def create_notification_by(current_user)
    # すでに「いいね」されているか検索
  temp = Notification.find_by(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
      notification.save if notification.valid?
    end

  end


  def create_notification_comment(current_user, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
  # ------------------------------------------------

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :post_set, only: [:show, :edit, :update, :destroy, :ensure_correct_user,:redirect_to_posts, :post_draft]
  before_action :ensure_correct_user, only: [:update, :edit, :destroy]
  before_action :authenticate_user!, only: [:new]
  before_action :redirect_to_posts, only: [:show]
  before_action :post_draft, only: [:show]
  before_action :is_valid_users, only: [:show]
  before_action :set_category_tag

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # params[:post][:tag_name]：formから、@postオブジェクトを参照してタグの名前も一緒に送信するコード
    # "ケーキ"　"プリン"　"タルト"のように送られて、取得する
    # split(",")は送信されてきた値を、スペースで区切って配列化する
    tag_list = params[:post][:tag_ids].split(/[[:space:]]/)
    if @post.save
      # 先ほど取得したタグの配列をsave_tagというインスタンスメソッドを使ってデータベースに保存する処理
      # save_tagインスタンスメソッドの中身はpost.rbで定義
      @post.save_tag(tag_list)
      flash[:notice] = "登録が完了しました。"
      redirect_to post_path(@post)
    else
     render :new
    end
  end

  def index
    case params[:sort]
    when "likes_count desc"
      to  = Time.current.at_end_of_day
      from  = (to - 6.day).at_beginning_of_day
      @posts = Post.where(status: 0).includes(:liked_users).sort {|a,b| b.liked_users.where(created_at: from...to).size <=> a.liked_users.where(created_at: from...to).size}
    when "followings desc"
      @posts = Post.where(user_id: [current_user.id, *current_user.following_ids], status: 0).order(created_at: :desc)
    else
      @posts = Post.order(created_at: :desc).where(status: 0)
    end
  end

  def show
    @lat = @post.latitude
    @lng = @post.longitude
    gon.lat = @lat
    gon.lng = @lng
    @post_comment = PostComment.new
    @user = @post.user
  end

  def edit
    @lat = @post.latitude
    @lng = @post.longitude
    gon.lat = @lat
    gon.lng = @lng
    @tag_lists = @post.tags.pluck(:name).join(" ")
  end

  def update
    tag_list = params[:post][:tag_ids].split(/[[:space:]]/)
    if @post.update(post_params)
      @post.save_tag(tag_list)
      flash[:notice] = "変更を保存しました。"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:image, :introduction, :category_id, :address, :latitude, :longitude, :start_time, :status)
  end

  def post_set
    @post = Post.find_by(id: params[:id])
  end


  def ensure_correct_user
    unless @post.user == current_user
      redirect_to posts_path
    end
  end

  def redirect_to_posts
    if @post.blank?
      redirect_to posts_path
    end
  end

  def post_draft
    unless @post.status == "投稿する"
      unless @post.user == current_user
        redirect_to posts_path
      end
    end
  end

  def is_valid_users
    @post = Post.find_by(id: params[:id])
    unless @post.user.is_valid == false
      redirect_to posts_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def post_button
    if action_name == "new"
      "登録する"
    elsif action_name == "edit"
      "変更を保存"
    elsif action_name == "create"
      "登録する"
    else action_name == "update"
      "変更を保存"
    end
  end

end

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>

 <% if post.errors.any? %>
   <div id= error_explanation >
    <h2><%= pluralize(post.errors.count, "件") %> のエラーが発生しました。</h2>
    <ul>
     <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
     </ul>
    </div>
  <% end %>

  <div class="post-actions__form-field image-field">
    <p class="post-actions__form-field--title">画像を登録</p>
    <%= attachment_image_tag post, :image, fallback: "no-image.png", id: "img_prev", class: "post-actions__form-field--image" %><br />
    <%= f.attachment_field :image %>
  </div>
  <div class="post-actions__form-field introduction-field">
    <p class="post-actions__form-field--title">投稿追加</p>
    <%= f.text_area :introduction, class: "post-actions__form-field--introduction" , id: "post-introduction" %>
  </div>

  <div class="post-actions__form-field category-field">
    <p class="post-actions__form-field--title">カテゴリー選択</p>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, class: "post-actions__form-field--category" ) %>
  </div>

  <div class="post-actions__form-field tag-field">
    <p class="post-actions__form-field--title">タグを追加</p>
  <%= f.text_field :tag_ids, value: @tag_lists, class: "form-control", id: 'tag_ids',\
  placeholder: "タグをつけるには全角スペースで区切ってください", class: "post-actions__form-field--tag" %>
  </div>

  <div class="post-actions__form-field calemdar-field">
    <p class="post-actions__form-field--title">カレンダーの日付登録</p>
    <%= f.date_field :start_time, class: "post-actions__form-field--calemdar" %>
  </div>
  <div class="post-actions__form-field address-field">
    <p class="post-actions__form-field--title">住所を登録</p>
    <%= f.text_field :address, id: "address", class: "post-actions__form-field--address" %>
    <input type="button" value="検索" onclick="codeAddress()" class="form-btn">
  </div>

  <% if post.address.blank? %>
    <div id='map'></div>
  <% else %>
    <div id='show_map'></div>
  <% end %>

  <% if post.status == "下書きする" %>
    <div class="status-field">
      <%= f.radio_button :status, "投稿する" %>
      <%= f.label :status_0, '投稿する'  %>
      <%= f.radio_button :status, "下書きする"%>
      <%= f.label :status_1, '下書きする' %>
    </div>
  <% end %>

  <%= f.submit post_button, class: "actions-btn" %>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
  <%  unless post.user.is_valid == true %>
    <div class="post-index__posts--link">
      <%= link_to post_path(post.id) do %>
        <%= attachment_image_tag post, :image, size: "300x200"  %>
        <div class="post-index__posts--introduction">
          <p class="post-index__posts--introduction--user">
            <%= attachment_image_tag post.user, :profile_image, size: "30x30", fallback: "no_image.jpg", class: "post-index__posts--introduction--user-image" %>
            <%= post.user.name %>
          </p>
          <p class="post-index__posts--introduction--title">
            <%= post.introduction.truncate(30)  %>
          </p>
          <p class="post-index__posts--introduction--create">
            <spna class="fas fa-heart like"><%= post.likes.count %></spna>
            <spna class="created_"><%= post.created_at.strftime('%Y.%m.%d') %></spna>
          </p>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/_post-links.html.erb
<ul>
  <li class="post-index__posts-links--item">
    <%= link_to "新着順" %>
  </li>
  <li class="post-index__posts-links--item">
    <%= link_to "人気順", sort: 'likes_count desc' %>
  </li>
  <li class="post-index__posts-links--item">
    <% if user_signed_in? %>
      <%= link_to "フォロワー", sort: 'followings desc' %>
    <% end %>
  </li>
</ul>

app/views/posts/_side-var.html.erb
<div class="side-var__list">
  <p class="side-var__title">
    カテゴリー検索
  </p>
  <ul class="side-var__list-name">
    <% categorys.each do |category| %>
      <li class="side-var__list-link">
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
  </ul>
</div>
<div class="side-var__list side-var__list--sticky">
  <p class="side-var__title">
      タグ検索
  </p>
  <ul class="side-var__list-name">
    <% tag_list.each do |tag| %>
      <li class="side-var__list-link">
       <%= link_to tag_path(tag.id) do %>
          #<%= tag.name %>
        <% end %>
      </li>
    <% end %>
    <%= link_to tags_path do %>
      タグ一覧はこちらから>>
    <% end %>
  </ul>
</div>

app/views/posts/edit.html.erb
<div class="main-post">
  <div class="post-actions">
    <div class="post-actions__title">
      <h2 class="title">Sweet Post</h2>
    </div>
    <div class="post-actions__form">
      <%= render 'form',  post: @post %>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main-post">
  <p id="notice">
   <% if flash[:notice] %>
    <%= flash[:notice] %>
   <% end %>
  </p>
  <div class="main-post-row">
    <div class="post-index">
      <div class="post-index__title">
        <h2 class="title">Post List</h2>
      </div>
      <!--投稿並べ替えリンク-->
      <div class="post-index__posts-links">
        <%= render 'post-links' %>
      </div>
      <!--投稿一覧-->
      <div class="post-index__posts">
        <%= render 'index', posts: @posts %>
      </div>
    </div>
    <div class="side-var">
      <%= render 'side-var', categorys: @categorys, tag_list: @tag_list %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main-post">
  <div class="post-actions">
    <div class="post-actions__title">
      <h2 class="title">Sweet Post</h2>
    </div>
    <div class="post-actions__form">
      <%= render 'form',  post: @post %>
    </div>
      <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-post">

  <div class="post-show">
    <p id="notice">
     <% if flash[:notice] %>
      <%= flash[:notice] %>
     <% end %>
    </p>
    <div>
      <%=  attachment_image_tag @post, :image, format: 'jpg', class: "post-show__image" %>
    </div>

    <!--showページhaeder-->
    <div class="post-show__info">
      <!--ユーザー-->
      <div class="post-show__info-user">
        <%= link_to(user_path(@user.id), class: 'post-show__info-user--link') do %>
            <%= attachment_image_tag  @user, :profile_image, format: 'jpg', fallback: "no_image.jpg" , class: "post-show__info-user--image" %>
          <div class="post-show__info-user--name">
            <%= @user.name %>
          </div>
        <% end %>
      </div>

      <div class="post-show__info-list">
        <!--いいね機能-->
        <div class="post-show__info-list--like">
          <div id="likes_buttons_<%= @post.id %>">
            <%= render partial: 'likes/likes', locals: { post: @post } %>
          </div>
        </div>
        <!--カテゴリーリンク-->
        <div class="post-show__info-list--category">
          <span class="post-show__info-list--name">カテゴリー：</span>
          <%= link_to @post.category.name, category_path(@post.category)  %>
        </div>
        <!--投稿日-->
        <div class="post-show__info-list--creat">
          <span class="post-show__info-list--name">投稿日時：</span>
          <%= @post.created_at.strftime('%Y.%m.%d') %>
        </div>
      </div>
    </div>

    <!--showページmain-->
    <div class="post-show__content">
      <div class="post-show__content-main">
        <%= safe_join("#{@post.introduction}".split("\n"),tag(:br))%>
      </div>
      <div class="post-show__content-tag">
        <% @post.tags.each do |tag| %>
          <%= link_to tag_path(tag.id) do %>
            #<%= tag.name %>
          <% end %>
        <% end %>
      </div>
    </div>

    <!--showページ地図機能-->
    <% if @post.address.present? %>
      <div class="post-show__adress">
        住所：<%= @post.address %>
      </div>
      <div id="show_map"></div>
    <% end %>

    <!--showページ編集・削除機能-->
    <div class="post-show__edit-destroy">
      <% if @post.user == current_user %>
        <%= link_to "" , edit_post_path(@post), class: "post-show__edit far fa-edit fa-lg" %>
        <%= link_to "" , post_path(@post),  method: :delete, data: { confirm: '本当に消しますか？' }, class: "post-show__destroy far fa-trash-alt fa-lg" %>
      <% end %>
    </div>

    <!--コメント機能-->
    <div class="post-show__comments">
      <div id="comments-area_<%= @post.id %>">
        <%= render "post_comments/post_comments", post: @post  %>
      </div>
      <div class="new-comment-area">
        <% if user_signed_in? %>
          <%= form_with(model:[@post,@post_comment], class: "comment-form") do |f| %>
            <%= f.text_area :comment,placeholder: "コメントをここに", class: "new-comment" %>
            <%= f.submit "送信する", class: "actions-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="back">
      <%= link_to '<< 戻る', :back %>
    </div>
  </div>
</div>