config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/search', to: 'search#search'
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy, :patch]
  end
  resources :tags, only: [:index, :show]
  resources :categorys, only: [:show]
  resources :users, only: [:show,:index,:edit,:update,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'calendar', to: 'users#calendar'
    put 'hide' => 'users#hide', as: 'users_hide'
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: [:index, :destroy]
  resources :chats, only: [:show, :create]

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer-bar">
  <footer id="footer">
    <p id="page-top"><a href="#"><%= image_tag 'top.png', class: "top-page" %></a></p>
  </footer>
    <ul class="sns">
      <li class="fab fa-facebook-f"></li>
      <li class="fab fa-twitter"></li>
      <li class="fab fa-instagram"></li>
    </ul>
    <div class="copyright">
      Copyright © T_SweetDiary. <br >
      All rights reserved.
    </div>
  </div>
</footer>

<script>
function PageTopAnime() {
	var scroll = $(window).scrollTop();
	if (scroll >= 200){//上から200pxスクロールしたら
		$('#page-top').removeClass('DownMove');//#page-topについているDownMoveというクラス名を除く
		$('#page-top').addClass('UpMove');//#page-topについているUpMoveというクラス名を付与
	}else{
		if($('#page-top').hasClass('UpMove')){//すでに#page-topにUpMoveというクラス名がついていたら
			$('#page-top').removeClass('UpMove');//UpMoveというクラス名を除き
			$('#page-top').addClass('DownMove');//DownMoveというクラス名を#page-topに付与
		}
	}
}

// 画面をスクロールをしたら動かしたい場合の記述
$(window).scroll(function () {
  // スクロールした際の動きの関数を呼ぶ
	PageTopAnime();
});

// #page-topをクリックした際の設定
$('#page-top a').click(function () {
    $('body,html').animate({
        scrollTop: 0//ページトップまでスクロール
    }, 800);//ページトップスクロールの速さ。数字が大きいほど遅くなる
    event.preventDefault() //aタグの機能を無効にするメソッド
});

</script>

app/views/layouts/_header.html.erb
<header class="header">
  <h1 class="header__logo">
    <a class="header__logo-link" href="/" ><%= image_tag 'Logo.png', class: "logo" %></a>
  </h1>
  <nav class="header__navbar" id="sp-menu">
    <ul class="header__navbar-menu">
      <% if user_signed_in? %>
        <li class="header__navbar-men-title">
          <%= link_to "投稿一覧", posts_path %>
        </li>
        <li class="header__navbar-men-title dropdown">カテゴリー検索 ▼
          <ul class="side-var__list-name">
            <% @categorys.each do |category| %>
              <li class="side-var__list-link">
                <%= link_to category.name, category_path(category) %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="header__navbar-men-title dropdown">タグ検索 ▼
          <ul class="side-var__list-name">
            <% @tag_list.each do |tag| %>
              <li class="side-var__list-link">
               <%= link_to tag_path(tag.id) do %>
                  #<%= tag.name %>
                <% end %>
              </li>
            <% end %>
            <%= link_to tags_path do %>
              <li class="side-var__list-link">
                タグ一覧はこちらから>>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to "ユーザー一覧", users_path %>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to "新規投稿", new_post_path %>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to 'マイページ', user_path(current_user.id) %>
        </li>
        <li class="header__navbar-men-title">
        <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
        <% end %>
          <%= link_to '通知', notifications_path %>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="header__navbar-men-title">
          <%= link_to "投稿一覧", posts_path %>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li class="header__navbar-men-title">
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </ul>
    <ul class="header__navbar-menu header__search">
      <%= render 'layouts/search' %>
    </ul>
  </nav>

  <div id="hm-icon">
    <a class="menu-trigger" href="#">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
</header>

<!--レスポンシブ対応時のヘッダー カテゴリー、タグ検索時-->
<script>
$(function() {
  // .menu-triggerクリック時に行われる処理
  $('.menu-trigger').on('click', function(event) {
    // toggleClass()を設定すると、アイコンがクリックされたときにactiveクラスが追加され、もう一度クリックすると削除される
    $(this).toggleClass('active');
    // .fadeToggle()は、要素のフェードイン・フェードアウトを切り替えるメソッド
    $('#sp-menu').fadeToggle();
    event.preventDefault();
  });
});
</script>

app/views/layouts/_search.html.erb
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <div class="input-group">
    <%= f.text_field :keyword, placeholder: "キーワードで検索" %>
    <input type="submit" value="&#xf002; 検索" class="fas btn">
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TSweetdiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main><%= yield %></main>
    <%= render 'layouts/footer' %>
    <script src='//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js'></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
  </body>
</html>